services: 
  jenkins: 
    image: jenkins/jenkins
    ports: 
      - "88:8888"
    volumes: 
      - "./vol:/var/lib/jenkins/"
  tomcat: 
    image: tomcat
    ports: 
      - "80:8080"
    volumes: 
      - "./vol:/opt/tomcat/webapps/" 
version: "3"
